### ISSUE TITLE
research on c++ http servers

### ISSUE THREAD

**Issue by lgeorgieff** [lgeorgieff/translate#4]
* https://code.google.com/p/mongoose/
* https://bitbucket.org/Corvusoft/restbed/wiki/Home + http://programmers.stackexchange.com/questions/238171/c-web-development-for-rest-api
* http://www.gnu.org/software/libmicrohttpd/

**Comment by lgeorgieff** [comment]
* http://www.gnu.org/software/libmicrohttpd/
** to big (--)
** installation + integration to complicated (--)
* https://code.google.com/p/mongoose/
** very small (++)
** no uri templates/parameters (-)

**Comment by lgeorgieff** [comment]
Choice: https://code.google.com/p/mongoose/

**Comment by ben-crowhurst** [comment]
@lgeorgieff Thanks for this feedback :D

**many dependencies (--)**
We've a change making it's way up stream this coming week to reduce the number of dependencies.  However with SSL support on the way it's sure to increase again.  We aim to make the build/installation as painless as possible and will be supporting switches to disable unwanted features. 

**too big (--)**
Restbed weights in at 1.1 Megabyte.  What would you say is an ideal size?

**Comment by lgeorgieff** [comment]
Hey,
well I think your question is a little bit to generic. What is an ideal size of an HTTP-server?
Sometimes 500 KB can be too much, sometimes 100 MB are appropriate - it depends on the purpose of the project.

Indeed 1.1 MB are little (when I think on Apache it is nothing). But I was actually looking for a lightweight HTTP implementation with only basic functionality and VERY, VERY easy integration. So that it shouldn't be more than one header and one implementation file.

BR
lukas
